#!/bin/bash
# Regenerate the TypeScript wire types from the Rust source of truth (ts-rs).
#
# The Rust types in `common` (game state / events / commands) and `server`
# (the WSMessage protocol enum + lobby/chat structs) are the single definition
# of everything that crosses the WebSocket. This script derives their exact
# TypeScript shapes into client/web/types/generated/ so the client never
# hand-mirrors them again.
#
# Run after changing any wire type. CI runs this and fails on any diff.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/client/web/types/generated"

rm -rf "$OUT"
mkdir -p "$OUT"

# common: game state, events, commands, sync status.
TS_RS_EXPORT_DIR="$OUT" cargo test -p common --features ts-gen export_bindings -- --quiet
# server: the WSMessage protocol envelope + lobby/chat payloads (pulls in the
# common types via the chained `common/ts-gen` feature).
TS_RS_EXPORT_DIR="$OUT" cargo test -p server --features ts-gen export_bindings -- --quiet

# ts-rs can leave spaces at the ends of wrapped doc-comment lines. Normalize
# generated output so repository whitespace checks and regeneration CI agree.
perl -pi -e 's/[ \t]+$//' "$OUT"/*.ts

# Barrel: re-export every generated type so consumers can
# `import { GameState, WSMessage } from '../types/generated'`.
BARREL="$OUT/index.ts"
{
  echo "// AUTO-GENERATED by scripts/gen-types.sh. Do not edit."
  for f in "$OUT"/*.ts; do
    name="$(basename "$f" .ts)"
    [ "$name" = "index" ] && continue
    echo "export * from './$name';"
  done
} > "$BARREL"

echo "Generated $(ls "$OUT"/*.ts | grep -v '/index.ts' | wc -l | tr -d ' ') types into $OUT"
