// AUTO-GENERATED by client/design/tools/trace_rank_icons.py — do not edit by hand.
//
// Vector reproductions of the original raster rank icons
// (client/web/public/images/{tier}.png), traced facet-by-facet with
// fitted gradients on the source 200x200 canvas. Interior pixels match
// the rasters to within a mean channel delta of ~3/255; the only
// difference is the sub-pixel anti-aliasing band along edges.

export type RankIconTier =
  | 'bronze'
  | 'silver'
  | 'gold'
  | 'platinum'
  | 'diamond'
  | 'grandmaster'
  | 'unranked';

export interface RankIconGradientStop {
  offset: number;
  color: string;
}

export interface RankIconGradient {
  id: string;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  stops: RankIconGradientStop[];
}

export interface RankIconShape {
  d: string;
  /** Either a '#rrggbb' literal or a local 'url(#gN)' gradient reference. */
  fill: string;
}

export interface RankIconDefinition {
  gradients: RankIconGradient[];
  shapes: RankIconShape[];
}

export const RANK_ICON_VIEW_BOX = '0 0 200 200';

export const RANK_ICON_DATA: Record<RankIconTier, RankIconDefinition> = {
  bronze: {
    gradients: [
      { id: 'g0', x1: 141.0, y1: 101.4, x2: 128.2, y2: 74.7, stops: [{ offset: 0.0, color: '#a04f22' }, { offset: 0.167, color: '#a45123' }, { offset: 0.333, color: '#a75324' }, { offset: 0.5, color: '#a95525' }, { offset: 0.667, color: '#ac5826' }, { offset: 0.833, color: '#ae5927' }, { offset: 1.0, color: '#af5a28' }] },
      { id: 'g1', x1: 85.3, y1: 118.6, x2: 45.1, y2: 58.3, stops: [{ offset: 0.0, color: '#c46f32' }, { offset: 0.167, color: '#ca7637' }, { offset: 0.333, color: '#d17e3c' }, { offset: 0.5, color: '#d88642' }, { offset: 0.667, color: '#dd8c47' }, { offset: 0.833, color: '#e0904b' }, { offset: 1.0, color: '#e2934d' }] },
      { id: 'g2', x1: 136.3, y1: 140.5, x2: 124.9, y2: 126.5, stops: [{ offset: 0.0, color: '#753616' }, { offset: 0.167, color: '#763616' }, { offset: 1.0, color: '#883f19' }] },
      { id: 'g3', x1: 63.3, y1: 149.4, x2: 74.9, y2: 117.6, stops: [{ offset: 0.0, color: '#98491e' }, { offset: 0.167, color: '#9e4d20' }, { offset: 0.333, color: '#a25022' }, { offset: 0.5, color: '#a95525' }, { offset: 0.667, color: '#b15d29' }, { offset: 0.833, color: '#ba652d' }, { offset: 1.0, color: '#c77336' }] },
      { id: 'g4', x1: 93.0, y1: 71.4, x2: 36.6, y2: 65.9, stops: [{ offset: 0.0, color: '#efa560' }, { offset: 0.167, color: '#f4ae6c' }, { offset: 0.333, color: '#f7b676' }, { offset: 0.5, color: '#f9bc7f' }, { offset: 0.667, color: '#fbc287' }, { offset: 0.833, color: '#fbc58b' }, { offset: 1.0, color: '#fcc68d' }] },
      { id: 'g5', x1: 138.2, y1: 80.3, x2: 130.7, y2: 58.5, stops: [{ offset: 0.0, color: '#d78541' }, { offset: 0.167, color: '#db8944' }, { offset: 0.333, color: '#dd8c47' }, { offset: 0.5, color: '#e08f49' }, { offset: 0.667, color: '#e3924c' }, { offset: 0.833, color: '#e3934d' }, { offset: 1.0, color: '#e4944e' }] },
    ],
    shapes: [
      { d: 'M102 182.5L97 182.5L30.5 129L29.5 126L29.5 87L22.5 80L22.5 31L27 27.5L36 32.5L99 82.5L115 71.5L167 29.5L172 27.5L177.5 32L177.5 79L169.5 87L169.5 127L168.5 130Z', fill: '#171e21' },
      { d: 'M101 130.5L99.5 126L100.5 122L99.5 121L100.5 118L99.5 117L100.5 112L99.5 111L100.5 109L99.5 100L168 46.5L169.5 49L169.5 76Z', fill: 'url(#g0)' },
      { d: 'M100 130.5L92 125.5L30.5 76L31 47.5L33 47.5L41 53.5L99.5 100Z', fill: 'url(#g1)' },
      { d: 'M101 173.5L99.5 172L100.5 167L99.5 142L160 94.5L161.5 97L161.5 125Z', fill: 'url(#g2)' },
      { d: 'M99 172.5L58 141.5L38.5 125L39 94.5L51 102.5L99.5 141L100.5 167Z', fill: 'url(#g3)' },
      { d: 'M100 99.5L41 53.5L33 47.5L31 47.5L30.5 41L33 40.5L95 89.5L99.5 94Z', fill: 'url(#g4)' },
      { d: 'M102 98.5L99.5 96L101 92.5L164 42.5L167 40.5L168.5 41L169.5 44L168 46.5Z', fill: 'url(#g5)' },
    ],
  },
  silver: {
    gradients: [
      { id: 'g0', x1: 66.4, y1: 134.6, x2: 148.0, y2: 27.3, stops: [{ offset: 0.0, color: '#1f2525' }, { offset: 0.167, color: '#202626' }, { offset: 0.333, color: '#1e2425' }, { offset: 0.5, color: '#212727' }, { offset: 1.0, color: '#1f2526' }] },
      { id: 'g1', x1: 60.7, y1: 102.8, x2: 70.4, y2: 54.3, stops: [{ offset: 0.0, color: '#c0c9ca' }, { offset: 0.167, color: '#c6ced0' }, { offset: 0.333, color: '#ccd4d5' }, { offset: 0.5, color: '#d5dbdb' }, { offset: 0.667, color: '#d9dfdf' }, { offset: 0.833, color: '#dde2e2' }, { offset: 1.0, color: '#e3e6e6' }] },
      { id: 'g2', x1: 135.0, y1: 135.7, x2: 123.8, y2: 121.0, stops: [{ offset: 0.0, color: '#7c888b' }, { offset: 0.167, color: '#7d888c' }, { offset: 0.333, color: '#7d898c' }, { offset: 0.5, color: '#7d898d' }, { offset: 0.667, color: '#7e8a8d' }, { offset: 1.0, color: '#8e9b9e' }] },
      { id: 'g3', x1: 65.9, y1: 147.9, x2: 74.3, y2: 108.4, stops: [{ offset: 0.0, color: '#abb5b8' }, { offset: 0.167, color: '#b0babc' }, { offset: 0.333, color: '#b6bfc1' }, { offset: 0.5, color: '#bfc8c9' }, { offset: 0.667, color: '#c6cdcf' }, { offset: 0.833, color: '#ccd3d4' }, { offset: 1.0, color: '#d4dada' }] },
    ],
    shapes: [
      { d: 'M101 177.5L98 177.5L95 175.5L36 127.5L31.5 122L31.5 83L22.5 74L22.5 24L26 20.5L32 21.5L98 74.5L101 74.5L104 72.5L169 20.5L174 20.5L177.5 25L177.5 73L167.5 83L167.5 123L166.5 125Z', fill: 'url(#g0)' },
      { d: 'M99 124.5L31.5 71L32 33.5L38 36.5L100.5 86L99.5 87Z', fill: 'url(#g1)' },
      { d: 'M102 124.5L99.5 124L99.5 92L168 38.5L169.5 40L169.5 69L168.5 71Z', fill: '#909da1' },
      { d: 'M101 167.5L99.5 167L99.5 136L158 89.5L159.5 91L159.5 120Z', fill: 'url(#g2)' },
      { d: 'M99 166.5L95 164.5L40.5 120L41 90.5L43 90.5L51 96.5L99.5 136Z', fill: 'url(#g3)' },
      { d: 'M100 91.5L99.5 87L105 81.5L163 35.5L167 32.5L168.5 33L169.5 36L168 38.5Z', fill: '#b3bdbf' },
    ],
  },
  gold: {
    gradients: [
      { id: 'g0', x1: 139.8, y1: 103.9, x2: 130.1, y2: 59.0, stops: [{ offset: 0.0, color: '#efaa26' }, { offset: 0.167, color: '#f0ac27' }, { offset: 0.333, color: '#f1ae29' }, { offset: 0.5, color: '#f2b02a' }, { offset: 0.667, color: '#f3b12b' }, { offset: 0.833, color: '#f3b32c' }, { offset: 1.0, color: '#f4b42d' }] },
      { id: 'g1', x1: 67.3, y1: 111.9, x2: 64.6, y2: 52.8, stops: [{ offset: 0.0, color: '#fbc63a' }, { offset: 0.167, color: '#fcc93c' }, { offset: 0.333, color: '#fccc40' }, { offset: 0.5, color: '#fdcf44' }, { offset: 0.667, color: '#fdd147' }, { offset: 0.833, color: '#fed248' }, { offset: 1.0, color: '#fed349' }] },
      { id: 'g2', x1: 85.4, y1: 87.1, x2: 45.3, y2: 36.3, stops: [{ offset: 0.0, color: '#fde477' }, { offset: 0.167, color: '#fde67f' }, { offset: 0.333, color: '#fee888' }, { offset: 0.5, color: '#feeb91' }, { offset: 0.667, color: '#feec9b' }, { offset: 0.833, color: '#feeea2' }, { offset: 1.0, color: '#fdefa5' }] },
      { id: 'g3', x1: 129.8, y1: 87.1, x2: 138.1, y2: 36.7, stops: [{ offset: 0.0, color: '#fdd246' }, { offset: 0.167, color: '#fdd346' }, { offset: 0.333, color: '#fed548' }, { offset: 0.5, color: '#fed649' }, { offset: 0.667, color: '#fed64a' }, { offset: 0.833, color: '#fed649' }, { offset: 1.0, color: '#fed74a' }] },
      { id: 'g4', x1: 68.3, y1: 120.7, x2: 73.4, y2: 111.5, stops: [{ offset: 0.0, color: '#fac738' }, { offset: 0.167, color: '#fbca3a' }, { offset: 0.333, color: '#fbcb3b' }, { offset: 0.5, color: '#fccc3b' }, { offset: 0.667, color: '#fccb3b' }, { offset: 0.833, color: '#fcca3c' }, { offset: 1.0, color: '#fbca3c' }] },
    ],
    shapes: [
      { d: 'M102 178.5L97 178.5L92 174.5L39 130.5L31.5 122L31.5 83L22.5 74L22.5 24L26 20.5L30 20.5L36 24.5L99 75.5L102 74.5L169 20.5L174 20.5L177.5 25L177.5 73L167.5 83L167.5 123L164 127.5Z', fill: '#242e33' },
      { d: 'M101 125.5L100.5 97L99.5 96L100.5 94L99.5 92L168 38.5L169.5 40L169.5 70L168.5 72Z', fill: 'url(#g0)' },
      { d: 'M100 125.5L98 125.5L31.5 72L32 38.5L92 86.5L99.5 91L100.5 94L99.5 95L100.5 97Z', fill: 'url(#g1)' },
      { d: 'M101 169.5L98.5 168L99.5 166L99.5 142L159 95.5L159.5 120Z', fill: '#d68218' },
      { d: 'M98 167.5L40.5 120L41 96.5L46 98.5L97 140.5L99.5 141L99.5 166Z', fill: '#efaa26' },
      { d: 'M99 90.5L92 86.5L32 38.5L31.5 34L34 33.5L38 36.5L98 84.5L99.5 86Z', fill: 'url(#g2)' },
      { d: 'M100 91.5L100 85.5L112 77.5L166 33.5L168.5 34L169.5 36L168 38.5Z', fill: 'url(#g3)' },
      { d: 'M99 140.5L97 140.5L46 98.5L41 96.5L40.5 91L44 91.5L99 135.5L100.5 137Z', fill: 'url(#g4)' },
      { d: 'M100 141.5L99.5 138L105 132.5L155 92.5L158 90.5L159.5 92L159.5 94L155 98.5Z', fill: '#e9a221' },
    ],
  },
  platinum: {
    gradients: [
      { id: 'g0', x1: 64.9, y1: 155.5, x2: 137.3, y2: 25.7, stops: [{ offset: 0.0, color: '#293435' }, { offset: 0.167, color: '#2a3536' }, { offset: 0.333, color: '#293535' }, { offset: 0.5, color: '#2b3637' }, { offset: 0.833, color: '#2c3838' }, { offset: 1.0, color: '#2e393a' }] },
      { id: 'g1', x1: 135.7, y1: 129.3, x2: 146.7, y2: 52.5, stops: [{ offset: 0.0, color: '#b2bbbb' }, { offset: 0.167, color: '#b5bdbe' }, { offset: 0.333, color: '#b9c1c1' }, { offset: 0.5, color: '#bdc4c4' }, { offset: 0.667, color: '#c0c7c7' }, { offset: 0.833, color: '#c3c9c9' }, { offset: 1.0, color: '#c5cbcb' }] },
      { id: 'g2', x1: 137.2, y1: 151.8, x2: 125.6, y2: 136.6, stops: [{ offset: 0.0, color: '#a1acad' }, { offset: 0.167, color: '#a3adae' }, { offset: 0.333, color: '#a3aeaf' }, { offset: 0.5, color: '#a4aeaf' }, { offset: 0.833, color: '#a4afb0' }, { offset: 1.0, color: '#adb7b7' }] },
      { id: 'g3', x1: 62.7, y1: 150.4, x2: 74.2, y2: 136.6, stops: [{ offset: 0.0, color: '#ccd2d1' }, { offset: 0.333, color: '#cdd2d1' }, { offset: 0.5, color: '#cdd3d2' }, { offset: 0.667, color: '#ced3d2' }, { offset: 0.833, color: '#ced4d3' }, { offset: 1.0, color: '#dadedc' }] },
      { id: 'g4', x1: 103.9, y1: 88.4, x2: 116.4, y2: 90.2, stops: [{ offset: 0.0, color: '#738383' }, { offset: 0.167, color: '#758485' }, { offset: 0.333, color: '#758585' }, { offset: 0.5, color: '#778686' }, { offset: 0.667, color: '#788888' }, { offset: 0.833, color: '#798889' }, { offset: 1.0, color: '#7a8a8a' }] },
      { id: 'g5', x1: 86.8, y1: 90.4, x2: 94.1, y2: 87.6, stops: [{ offset: 0.0, color: '#a4aeae' }, { offset: 0.167, color: '#a5afaf' }, { offset: 0.333, color: '#a7b0b1' }, { offset: 0.833, color: '#a7b1b1' }, { offset: 1.0, color: '#a8b1b2' }] },
      { id: 'g6', x1: 154.7, y1: 54.2, x2: 157.7, y2: 57.3, stops: [{ offset: 0.0, color: '#eef1f0' }, { offset: 0.333, color: '#f0f2f1' }, { offset: 0.5, color: '#f1f2f1' }, { offset: 0.667, color: '#f2f3f2' }, { offset: 0.833, color: '#f3f4f3' }, { offset: 1.0, color: '#f2f4f3' }] },
    ],
    shapes: [
      { d: 'M101 196.5L98 196.5L94 193.5L28.5 134L28.5 95L13.5 81L13.5 25L15 23.5L17 22.5L20 23.5L60 57.5L98 1.5L101 1.5L104.5 5L140 57.5L180 23.5L184 23.5L186.5 26L186.5 80L181 86.5L171.5 94L171.5 133Z', fill: 'url(#g0)' },
      { d: 'M100 143.5L95 141.5L20.5 77L20.5 41L23 38.5L60 69.5L66 72.5L67.5 76L71.5 79L100.5 114L99.5 119Z', fill: '#d6dbd9' },
      { d: 'M103 142.5L99.5 141L100.5 132L99.5 131L100.5 130L99.5 119L101.5 112L123.5 85L137 71.5L177 38.5L179.5 43L179.5 77L178.5 79L163 92.5L160 93.5L157 97.5L155 97.5L149 102.5Z', fill: 'url(#g1)' },
      { d: 'M104 184.5L101 184.5L99.5 183L99.5 159L100.5 158L99.5 154L104 151.5L145 115.5L150 113.5L162 103.5L164.5 109L164.5 127L162.5 132Z', fill: 'url(#g2)' },
      { d: 'M100 185.5L97 185.5L36.5 131L37 102.5L42 104.5L99.5 154L100.5 156L99.5 159Z', fill: 'url(#g3)' },
      { d: 'M101 90.5L99.5 90L99.5 17L98.5 16L100 14.5L102.5 16L133.5 62L132.5 65L125 72.5L121 73.5Z', fill: '#c5cbcb' },
      { d: 'M99 89.5L97 89.5L80 74.5L78 74.5L66.5 63L72.5 52L93.5 21L98 16.5L99.5 17Z', fill: '#f1f3f2' },
      { d: 'M101 103.5L99.5 103L99.5 92L117 76.5L123 73.5L123.5 76Z', fill: 'url(#g4)' },
      { d: 'M99 102.5L95.5 100L80.5 81L77.5 77L78 74.5L80 74.5L97 89.5L100.5 91Z', fill: 'url(#g5)' },
      { d: 'M133 77.5L131.5 75L134 71.5L177 35.5L179.5 37L178 40.5L175 41.5L159 54.5Z', fill: 'url(#g6)' },
    ],
  },
  diamond: {
    gradients: [
      { id: 'g0', x1: 132.3, y1: 36.7, x2: 68.4, y2: 143.8, stops: [{ offset: 0.0, color: '#29383d' }, { offset: 0.333, color: '#29393d' }, { offset: 0.5, color: '#2a393d' }, { offset: 0.667, color: '#2a393e' }, { offset: 0.833, color: '#2b3a3e' }, { offset: 1.0, color: '#2a3d43' }] },
      { id: 'g1', x1: 156.7, y1: 113.4, x2: 127.1, y2: 72.4, stops: [{ offset: 0.0, color: '#0890e2' }, { offset: 0.333, color: '#0891e2' }, { offset: 0.5, color: '#0992e3' }, { offset: 0.667, color: '#0b99e7' }, { offset: 0.833, color: '#0fa5ed' }, { offset: 1.0, color: '#12adf1' }] },
      { id: 'g2', x1: 116.2, y1: 107.9, x2: 79.2, y2: 105.7, stops: [{ offset: 0.0, color: '#11aef2' }, { offset: 0.167, color: '#09acf3' }, { offset: 0.333, color: '#06adf4' }, { offset: 0.5, color: '#18b9f9' }, { offset: 0.667, color: '#17b9f9' }, { offset: 0.833, color: '#13b7f8' }, { offset: 1.0, color: '#10b6f8' }] },
      { id: 'g3', x1: 50.5, y1: 120.7, x2: 72.5, y2: 89.8, stops: [{ offset: 0.0, color: '#21baf7' }, { offset: 0.167, color: '#24bcf8' }, { offset: 0.333, color: '#26bef9' }, { offset: 0.5, color: '#28c0fa' }, { offset: 0.667, color: '#2ac2fb' }, { offset: 0.833, color: '#2cc3fb' }, { offset: 1.0, color: '#2ec4fc' }] },
      { id: 'g4', x1: 105.9, y1: 73.0, x2: 94.4, y2: 49.6, stops: [{ offset: 0.0, color: '#12b3f5' }, { offset: 0.167, color: '#0eb1f5' }, { offset: 0.333, color: '#0eb3f6' }, { offset: 0.5, color: '#0fb4f7' }, { offset: 0.667, color: '#0fb5f7' }, { offset: 0.833, color: '#10b6f8' }, { offset: 1.0, color: '#12b7f8' }] },
      { id: 'g5', x1: 124.7, y1: 61.6, x2: 129.9, y2: 40.6, stops: [{ offset: 0.0, color: '#46d6ff' }, { offset: 0.167, color: '#46d7ff' }, { offset: 0.5, color: '#47d7ff' }, { offset: 0.667, color: '#48d7ff' }, { offset: 0.833, color: '#4bd8ff' }, { offset: 1.0, color: '#4dd9ff' }] },
      { id: 'g6', x1: 66.1, y1: 60.9, x2: 77.9, y2: 38.1, stops: [{ offset: 0.0, color: '#48d8ff' }, { offset: 0.167, color: '#49d8ff' }, { offset: 0.5, color: '#4cd9ff' }, { offset: 0.667, color: '#4dd9ff' }, { offset: 0.833, color: '#4fdaff' }, { offset: 1.0, color: '#54dbff' }] },
      { id: 'g7', x1: 34.0, y1: 59.8, x2: 60.1, y2: 61.8, stops: [{ offset: 0.0, color: '#69e0ff' }, { offset: 0.167, color: '#70e3ff' }, { offset: 0.333, color: '#74e4ff' }, { offset: 0.5, color: '#77e6ff' }, { offset: 0.667, color: '#7be7ff' }, { offset: 0.833, color: '#7ee8ff' }, { offset: 1.0, color: '#81e9ff' }] },
      { id: 'g8', x1: 96.1, y1: 76.4, x2: 95.9, y2: 71.3, stops: [{ offset: 0.0, color: '#5bcdf8' }, { offset: 0.167, color: '#60d3fa' }, { offset: 0.333, color: '#65dbfd' }, { offset: 0.5, color: '#6de0fe' }, { offset: 0.667, color: '#75e3ff' }, { offset: 1.0, color: '#78e4ff' }] },
      { id: 'g9', x1: 125.2, y1: 99.5, x2: 121.1, y2: 97.9, stops: [{ offset: 0.0, color: '#3bc6f8' }, { offset: 0.167, color: '#3fccfb' }, { offset: 0.333, color: '#41cefc' }, { offset: 0.5, color: '#45d2fe' }, { offset: 0.667, color: '#44d1fd' }, { offset: 0.833, color: '#49d2fd' }, { offset: 1.0, color: '#4ed1fc' }] },
      { id: 'g10', x1: 88.4, y1: 111.3, x2: 75.0, y2: 112.7, stops: [{ offset: 0.0, color: '#60dcfe' }, { offset: 0.167, color: '#62dcfe' }, { offset: 0.333, color: '#67deff' }, { offset: 0.5, color: '#69dfff' }, { offset: 0.667, color: '#6ee1ff' }, { offset: 0.833, color: '#73e3ff' }, { offset: 1.0, color: '#79e5ff' }] },
      { id: 'g11', x1: 111.1, y1: 140.2, x2: 108.3, y2: 139.1, stops: [{ offset: 0.0, color: '#35c3f7' }, { offset: 0.167, color: '#37cafb' }, { offset: 0.333, color: '#38ccfd' }, { offset: 0.5, color: '#39ccfd' }, { offset: 0.667, color: '#3acdfe' }, { offset: 0.833, color: '#3ccdfd' }, { offset: 1.0, color: '#3ccdfd' }] },
      { id: 'g12', x1: 101.6, y1: 169.2, x2: 97.2, y2: 166.4, stops: [{ offset: 0.0, color: '#0c90d9' }, { offset: 0.25, color: '#24a9e2' }, { offset: 0.5, color: '#33b4e0' }, { offset: 0.75, color: '#31bdf0' }, { offset: 1.0, color: '#34c4f9' }] },
    ],
    shapes: [
      { d: 'M102 180.5L98 180.5L94.5 178L14.5 77L14.5 72L32.5 48L40.5 35L46 30.5L154 30.5L157.5 33L185.5 73L184.5 78L178.5 86L108.5 174Z', fill: 'url(#g0)' },
      { d: 'M104 165.5L102.5 164L102.5 161L111.5 136L111.5 133L117.5 123L132.5 78L132.5 70L140.5 58L147.5 44L152 39.5L175.5 71L176.5 76L113.5 156Z', fill: 'url(#g1)' },
      { d: 'M101 167.5L99 167.5L96.5 165L96.5 159L71.5 85L70.5 80L72 75.5L127 75.5L128.5 77L113.5 122L113.5 130L102.5 161L103.5 165Z', fill: 'url(#g2)' },
      { d: 'M96 164.5L88.5 158L35.5 90L25.5 79L22.5 75L25 71.5L26 72.5L65 72.5L66.5 74L67.5 78L71.5 82L76.5 101L78.5 104L90.5 144L96.5 159Z', fill: 'url(#g3)' },
      { d: 'M130 71.5L72 71.5L69.5 69L99 39.5L101 39.5L130.5 70Z', fill: 'url(#g4)' },
      { d: 'M132 71.5L102.5 42L101.5 40L103 38.5L149 38.5L150.5 40Z', fill: 'url(#g5)' },
      { d: 'M69 70.5L65.5 68L51.5 43L48.5 40L50 38.5L97 38.5L98.5 40Z', fill: 'url(#g6)' },
      { d: 'M66 72.5L26 72.5L24.5 71L48 39.5L51.5 43L67.5 70Z', fill: 'url(#g7)' },
      { d: 'M71 79.5L67.5 78L65.5 73L68 70.5L72 71.5L130.5 72L128 75.5L72 75.5Z', fill: 'url(#g8)' },
      { d: 'M114 127.5L113.5 122L124.5 87L126.5 84L128.5 77L127.5 76L132 71.5L132.5 78L117.5 123Z', fill: 'url(#g9)' },
      { d: 'M94 154.5L90.5 148L80.5 116L78.5 113L78.5 110L76.5 107L76.5 104L68.5 82L70 79.5L72.5 81L76.5 92L93.5 149L95.5 152Z', fill: 'url(#g10)' },
      { d: 'M107 149.5L105.5 147L113 126.5L115.5 129L109.5 146Z', fill: 'url(#g11)' },
      { d: 'M100 171.5L93.5 165L95 163.5L97 165.5L98 164.5L100 167.5L103 165.5L104.5 167Z', fill: 'url(#g12)' },
    ],
  },
  grandmaster: {
    gradients: [
      { id: 'g0', x1: 139.0, y1: 148.1, x2: 45.3, y2: 20.7, stops: [{ offset: 0.0, color: '#2d3a3a' }, { offset: 0.167, color: '#2b383a' }, { offset: 0.333, color: '#303c3b' }, { offset: 0.5, color: '#293739' }, { offset: 0.667, color: '#2d3a3a' }, { offset: 0.833, color: '#283639' }, { offset: 1.0, color: '#333f3d' }] },
      { id: 'g1', x1: 109.8, y1: 132.5, x2: 81.9, y2: 39.9, stops: [{ offset: 0.0, color: '#f5b930' }, { offset: 0.167, color: '#fac233' }, { offset: 0.333, color: '#fbc633' }, { offset: 0.5, color: '#fcc835' }, { offset: 0.667, color: '#fccd39' }, { offset: 0.833, color: '#fdd03d' }, { offset: 1.0, color: '#fdd240' }] },
      { id: 'g2', x1: 92.9, y1: 75.2, x2: 84.2, y2: 35.7, stops: [{ offset: 0.0, color: '#fde581' }, { offset: 0.167, color: '#fde583' }, { offset: 0.333, color: '#fde685' }, { offset: 0.5, color: '#fde787' }, { offset: 0.667, color: '#fde88a' }, { offset: 0.833, color: '#fde98c' }, { offset: 1.0, color: '#fde98e' }] },
      { id: 'g3', x1: 37.3, y1: 142.6, x2: 45.4, y2: 119.4, stops: [{ offset: 0.0, color: '#f7bf2f' }, { offset: 0.167, color: '#f8c130' }, { offset: 0.333, color: '#fac231' }, { offset: 0.667, color: '#fbc332' }, { offset: 0.833, color: '#fcc736' }, { offset: 1.0, color: '#fccb3a' }] },
      { id: 'g4', x1: 162.2, y1: 137.1, x2: 152.4, y2: 125.4, stops: [{ offset: 0.0, color: '#f5ba2f' }, { offset: 0.167, color: '#f6bb2f' }, { offset: 0.333, color: '#f7bb2f' }, { offset: 0.667, color: '#f7bc30' }, { offset: 0.833, color: '#f8bd30' }, { offset: 1.0, color: '#f9c135' }] },
      { id: 'g5', x1: 103.8, y1: 89.2, x2: 122.2, y2: 89.7, stops: [{ offset: 0.0, color: '#b06115' }, { offset: 0.167, color: '#b26215' }, { offset: 0.333, color: '#b56415' }, { offset: 0.5, color: '#b76616' }, { offset: 0.667, color: '#b96716' }, { offset: 0.833, color: '#ba6816' }, { offset: 1.0, color: '#bb6916' }] },
      { id: 'g6', x1: 190.8, y1: 54.6, x2: 188.0, y2: 54.6, stops: [{ offset: 0.0, color: '#5a4f2e' }, { offset: 0.167, color: '#e19c20' }, { offset: 0.333, color: '#e19e22' }, { offset: 0.5, color: '#da921f' }, { offset: 0.667, color: '#dd9923' }, { offset: 1.0, color: '#e4a528' }] },
      { id: 'g7', x1: 174.1, y1: 118.4, x2: 170.6, y2: 118.2, stops: [{ offset: 0.0, color: '#5d4b2e' }, { offset: 0.2, color: '#ac701d' }, { offset: 0.4, color: '#c47c18' }, { offset: 0.6, color: '#bd7618' }, { offset: 0.8, color: '#be7619' }, { offset: 1.0, color: '#c27c1d' }] },
      { id: 'g8', x1: 153.2, y1: 84.7, x2: 142.0, y2: 70.9, stops: [{ offset: 0.0, color: '#fadc66' }, { offset: 0.167, color: '#f9da6a' }, { offset: 0.333, color: '#fcdc6b' }, { offset: 0.5, color: '#fcdf70' }, { offset: 0.667, color: '#fde073' }, { offset: 0.833, color: '#fde582' }, { offset: 1.0, color: '#fbe588' }] },
      { id: 'g9', x1: 33.6, y1: 56.6, x2: 37.2, y2: 51.8, stops: [{ offset: 0.0, color: '#fde582' }, { offset: 0.167, color: '#fce582' }, { offset: 0.333, color: '#fbe481' }, { offset: 0.5, color: '#fbe482' }, { offset: 0.667, color: '#fbe583' }, { offset: 0.833, color: '#fce788' }, { offset: 1.0, color: '#fbe890' }] },
      { id: 'g10', x1: 9.1, y1: 67.4, x2: 10.9, y2: 67.3, stops: [{ offset: 0.0, color: '#cebb63' }, { offset: 0.5, color: '#fbdb67' }, { offset: 1.0, color: '#fcdd69' }] },
      { id: 'g11', x1: 136.3, y1: 114.4, x2: 146.8, y2: 123.3, stops: [{ offset: 0.0, color: '#be7017' }, { offset: 0.167, color: '#c37519' }, { offset: 0.333, color: '#cb7e1b' }, { offset: 0.5, color: '#d2861c' }, { offset: 0.667, color: '#d58a1e' }, { offset: 0.833, color: '#d58b1e' }, { offset: 1.0, color: '#d4891d' }] },
      { id: 'g12', x1: 155.8, y1: 143.5, x2: 158.3, y2: 147.4, stops: [{ offset: 0.0, color: '#bc7718' }, { offset: 0.167, color: '#be7a19' }, { offset: 0.333, color: '#c17a19' }, { offset: 0.5, color: '#c27b19' }, { offset: 0.667, color: '#c37b1a' }, { offset: 0.833, color: '#c47d1b' }, { offset: 1.0, color: '#c47d1a' }] },
    ],
    shapes: [
      { d: 'M100 166.5L91 160.5L64 135.5L62.5 161L57 165.5L52 165.5L18.5 135L17.5 132L18.5 131L17.5 127L18.5 126L18.5 97L17.5 96L18.5 95L1.5 78L1.5 20L4 17.5L7 17.5L10 19.5L62 64.5L60.5 55L62.5 52L94.5 12L98 8.5L101 8.5L103.5 10L138.5 54L139.5 57L137 65.5L192 17.5L196 17.5L197.5 19L197.5 80L181.5 94L181.5 133L180.5 135L148 165.5L142 165.5L136.5 160L136 135.5L105 163.5Z', fill: 'url(#g0)' },
      { d: 'M101 154.5L98 154.5L10.5 78L10.5 36L12 34.5L19 38.5L68.5 82L74.5 99L75.5 107L100 129.5L124.5 107L132.5 82L186 34.5L187.5 36L188.5 38L187.5 78Z', fill: 'url(#g1)' },
      { d: 'M102 86.5L99.5 86L100 19.5L103.5 22L130.5 56L130.5 59Z', fill: '#fdc935' },
      { d: 'M99 86.5L68.5 58L70.5 54L98 20.5L99.5 21Z', fill: 'url(#g2)' },
      { d: 'M53 154.5L47 151.5L27.5 133L27.5 108L29 106.5L39 112.5L54.5 127L55.5 146L54.5 153Z', fill: 'url(#g3)' },
      { d: 'M147 154.5L144.5 153L144.5 128L158 115.5L160 115.5L169 108.5L170.5 111L170.5 133Z', fill: 'url(#g4)' },
      { d: 'M101 115.5L99.5 115L99.5 89L128 61.5L129.5 64L118.5 98Z', fill: 'url(#g5)' },
      { d: 'M99 114.5L88 105.5L81.5 98L77.5 83L70.5 65L71 62.5L74 62.5L98 86.5L100.5 87Z', fill: '#e3951f' },
      { d: 'M189 77.5L187.5 77L188.5 38L186.5 35L189 32.5L191.5 37L190.5 76Z', fill: 'url(#g6)' },
      { d: 'M172 133.5L170.5 133L170.5 111L168.5 108L171 104.5L173 104.5L174.5 107L174.5 131Z', fill: 'url(#g7)' },
      { d: 'M101 130.5L99.5 128L124.5 104L131.5 80L190 28.5L191.5 30L191.5 33L190 34.5L189 33.5L133.5 83L126.5 107Z', fill: 'url(#g8)' },
      { d: 'M66 80.5L60 77.5L12 35.5L10.5 41L11.5 44L10 45.5L8.5 44L9.5 41L8.5 31L11 29.5L63 74.5L67.5 79Z', fill: 'url(#g9)' },
      { d: 'M10 76.5L8.5 75L9.5 68L8.5 59L10 57.5L11.5 59L10.5 61L11.5 62L10.5 65L11.5 75Z', fill: 'url(#g10)' },
      { d: 'M100 157.5L98.5 155L105 148.5L183 79.5L187 76.5L188.5 78Z', fill: 'url(#g11)' },
      { d: 'M27 108.5L25.5 107L25.5 104L27 102.5L31.5 106Z', fill: '#e3c956' },
      { d: 'M145 158.5L143.5 157L145 153.5L150 150.5L169 132.5L171.5 134Z', fill: 'url(#g12)' },
    ],
  },
  unranked: {
    gradients: [
    ],
    shapes: [
      { d: 'M99 195.5L94 195.5L27.5 137L27.5 101L21.5 96L19.5 92L19.5 24L22 20.5L26 20.5L29 22.5L55 45.5L70 28.5L85 21.5L102 20.5L115 23.5L128 31.5L138 45.5L166 21.5L171 20.5L173.5 23L173.5 94L165.5 102L165.5 137L162 141.5Z', fill: '#96a0a5' },
      { d: 'M113 136.5L101 130.5L93 130.5L86 133.5L83 136.5L80 135.5L27.5 90L27.5 35L29 33.5L52.5 53L53.5 55L52.5 66L58 71.5L81 71.5L85.5 68L88.5 60L94 55.5L100 55.5L105.5 60L106.5 64L104.5 71L86.5 89L81.5 99L80.5 119L85 123.5L108 123.5L112.5 120L114.5 107L131.5 91L138.5 80L141.5 68L140.5 55L143 51.5L163 34.5L165.5 35L165.5 91Z', fill: '#fbf9f5' },
      { d: 'M108 123.5L85 123.5L80.5 119L80.5 103L82.5 96L86.5 89L104.5 71L106.5 64L105.5 60L100 55.5L94 55.5L88.5 60L85.5 68L81 71.5L58 71.5L52.5 66L53.5 55L51.5 51L53.5 47L57.5 44L61.5 37L70 28.5L85 21.5L92 20.5L109 21.5L123 27.5L128.5 32L142.5 51L140.5 55L141.5 68L138.5 80L131.5 91L114.5 107L113.5 118Z', fill: '#293437' },
      { d: 'M105 116.5L88 116.5L87.5 107L88.5 101L91.5 95L108.5 78L111.5 73L112.5 59L109.5 53L103 48.5L94 47.5L87 50.5L83.5 54L79 63.5L59.5 63L60.5 54L66.5 42L77 32.5L92 27.5L106 28.5L113 30.5L120 34.5L129.5 45L133.5 58L133.5 68L130.5 79L126.5 85L109.5 101L105.5 109Z', fill: '#ffffff' },
      { d: 'M97 186.5L35.5 134L35.5 111L37 109.5L76.5 143L77.5 145L76.5 152L78.5 159L88 168.5L91 169.5L102 169.5L108 166.5L115.5 158L116.5 145L153 112.5L156 110.5L157.5 112L157.5 135Z', fill: '#fbf9f5' },
      { d: 'M102 169.5L88 168.5L78.5 159L76.5 152L77.5 147L76.5 143L82 136.5L93 130.5L101 130.5L110 134.5L117.5 143L115.5 158L108 166.5Z', fill: '#293437' },
      { d: 'M98 162.5L91 161.5L84.5 154L85.5 144L93 137.5L100 137.5L104 139.5L107.5 143L109.5 148L108.5 155L102 161.5Z', fill: '#ffffff' },
    ],
  },
};
