import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import type { AccountModalView } from './AccountModal';
import { HomeHeader } from './HomeHeader';
import { useAuth } from '../contexts/AuthContext';
import { api, isApiError } from '../services/api';
import { getWasm, initWasm } from '../wasm';
import GenerateSkinModal from './GenerateSkinModal';
import type { SkinSummary } from '../types/generated';

/**
 * The Skin Builder: a layers panel and a preview.
 *
 * Photoshop's left-hand side without its canvas tools — a stack you reorder and
 * an inspector for whatever is selected. The preview is output, never input.
 *
 * There is no Animations section, and its absence is the point rather than an
 * omission. Animation is not a feature a skin has; it is what happens when a
 * property's expression reads `time`. So every animatable field is a number
 * with an **fx** toggle, because a constant *is* a constant expression — the
 * two states are one value seen two ways.
 *
 * Every control is generated by walking the descriptor the Rust crate emits.
 * That crate destructures the whole v2 vocabulary in an exhaustiveness module,
 * so a variant added without a control breaks its build; the `never` assignment
 * at the end of {@link Control} is the same guarantee on this side. Between
 * them, the panel cannot drift from the object model the renderer runs.
 */

interface SkinBuilderProps {
  onOpenAuth: () => void;
  onOpenAccount: (view: AccountModalView) => void;
}

/** Mirrors `skin_schema::describe_v2::KindV2`. */
type KindV2 =
  | { control: 'color' }
  | { control: 'colorRef'; slots: Choice[] }
  | { control: 'text'; maxLength: number; charset?: string }
  | { control: 'toggle' }
  | { control: 'number'; min: number; max: number; step: number }
  | {
      control: 'expression';
      min: number;
      max: number;
      step: number;
      inputs: string[];
      site: string;
      siteLabel: string;
    }
  | { control: 'choice'; options: Choice[] }
  | { control: 'group'; children: FieldV2[] }
  | { control: 'optional'; children: FieldV2[] }
  | {
      control: 'list';
      itemLabel: string;
      itemDefault: unknown;
      minItems: number;
      maxItems: number;
      children: FieldV2[];
    }
  | { control: 'variant'; tag: string; options: Variant[] };

interface Choice {
  value: string;
  label: string;
  help?: string;
}

interface Variant {
  value: string;
  label: string;
  help?: string;
  default: Record<string, unknown>;
  children: FieldV2[];
}

interface FieldV2 {
  path: string;
  label: string;
  kind: KindV2;
  help?: string;
  default?: unknown;
}

interface SchemaV2 {
  document: FieldV2[];
  layer: FieldV2[];
  addLayer: Variant[];
  systemLayers: { name: string; position: string; help: string }[];
  limits: { maxLayers: number; maxOps: number; maxTextures: number };
}

interface Template {
  id: string;
  label: string;
  document: Document;
  /** The fixture role this card paints — see `Template::preview_role`. */
  previewRole: string;
}

interface Cost {
  ops: number;
  maxOps: number;
  layers: number;
  maxLayers: number;
}

type Document = Record<string, unknown>;
type Layer = Record<string, unknown>;

/** Read a dotted path out of an object. */
const read = (target: unknown, path: string): unknown =>
  path.split('.').reduce<unknown>((value, key) => {
    if (value === null || typeof value !== 'object') {
      return undefined;
    }
    return (value as Record<string, unknown>)[key];
  }, target);

/**
 * Write a dotted path, returning a new object.
 *
 * Copies down the path rather than mutating, so React sees a changed object.
 * Arrays are copied *as arrays*: a palette is an array of colour pairs, and
 * spreading one into an object turns `friendly: [a, b]` into `friendly: {0: a,
 * 1: b}`, which the schema then refuses as "expected an array of length 2" —
 * from a colour picker, which is not a message anybody could act on.
 */
const write = (target: unknown, path: string, next: unknown): unknown => {
  const [head, ...rest] = path.split('.');
  const container: Record<string, unknown> | unknown[] = Array.isArray(target)
    ? [...target]
    : { ...((target as Record<string, unknown> | null) ?? {}) };

  if (rest.length === 0) {
    (container as Record<string, unknown>)[head] = next;
    return container;
  }

  const child = (target as Record<string, unknown> | undefined)?.[head];
  const seed = child ?? (/^\d+$/.test(rest[0]) ? [] : {});
  (container as Record<string, unknown>)[head] = write(seed, rest.join('.'), next);
  return container;
};

/** Drop a dotted path. Used by the optional-section switch. */
const drop = (target: unknown, path: string): unknown => {
  const [head, ...rest] = path.split('.');
  const container: Record<string, unknown> | unknown[] = Array.isArray(target)
    ? [...target]
    : { ...((target as Record<string, unknown> | null) ?? {}) };
  if (rest.length === 0) {
    delete (container as Record<string, unknown>)[head];
    return container;
  }
  const child = (target as Record<string, unknown> | undefined)?.[head];
  if (child === undefined) {
    return container;
  }
  (container as Record<string, unknown>)[head] = drop(child, rest.join('.'));
  return container;
};

/**
 * Whether a value is a plain number rather than an expression.
 *
 * The fx toggle is a view over one value, so this is what decides which view to
 * show. Written as "does it parse as a number" rather than "is it a JS number",
 * because the schema accepts `0.5` and `"0.5"` as the same thing and an author
 * who typed one should not be handed the other's editor.
 */
const asConstant = (value: unknown): number | null => {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return value;
  }
  if (typeof value === 'string' && value.trim() !== '') {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : null;
  }
  return null;
};

/** The template previews: a long horizontal body, drawn small enough to sit in a card. */
const TEMPLATE_POSE = 'longer_than_head_gradient';
const TEMPLATE_CELL = 11;
const PREVIEW_PAD = 6;

interface Preview {
  pose: string;
  role: string;
  /** Never shown; this is the accessible name for the canvas. */
  label: string;
}

interface Slide {
  id: string;
  /** The accessible name for the whole slide. */
  label: string;
  /**
   * How wide the slide is in snake cells, gaps included.
   *
   * The deck divides the space it actually has by this to get a pixel size, so
   * a sidebar that is 240px on a laptop and 384px on a monitor draws the same
   * arrangement at two sizes instead of overflowing at one of them. A fixed
   * cell size cannot do that: 21 cells at 13px is 273px, which is wider than
   * the column has ever been.
   */
  widthCells: number;
  previews: Preview[];
}

/**
 * The preview deck: three slides, one question each.
 *
 * A skin has to survive more than one body, and the earlier strip tried to say
 * so by showing everything at once — which made it wide, made it need captions
 * to stay legible, and left it competing with the panel it exists to serve. A
 * deck asks one question per slide instead, and answers it with pictures only.
 *
 * Slide one is the colours, on four lengths, because the length is what decides
 * whether a pattern repeats enough to read and whether the head glow has
 * anywhere to fall off. Slide two is the awkward geometry — the branches the
 * painter genuinely treats differently. Slide three is the turn, which needs
 * the width to itself.
 */
const SLIDES: Slide[] = [
  {
    id: 'colours',
    label: 'The four free-for-all colours, on four body lengths',
    widthCells: 21,
    // All four are near the panel's width, tails flush left, and the lengths
    // run short, long, longest, middling — so the heads trace a rise to a peak
    // and back rather than a staircase. Four bodies at four *very* different
    // lengths compared the colours against different amounts of snake; at
    // these lengths the only thing that differs between rows is the colour,
    // which is what the slide is for.
    previews: [
      { pose: 'straight_16', role: 'ffa0', label: 'Sixteen cells' },
      { pose: 'straight_19', role: 'ffa1', label: 'Nineteen cells' },
      { pose: 'longer_than_head_gradient', role: 'ffa2', label: 'Twenty-one cells' },
      { pose: 'straight_18', role: 'ffa3', label: 'Eighteen cells' },
    ],
  },
  {
    id: 'shapes',
    label: 'The awkward bodies: just spawned, crossing itself, and a zig-zag',
    // Five cells of stacked bodies, nine of zig-zag, and the gap between.
    widthCells: 15,
    previews: [
      { pose: 'starting_length', role: 'own', label: 'Just spawned' },
      { pose: 'self_crossing', role: 'own', label: 'Crossing itself' },
      { pose: 'zigzag', role: 'own', label: 'Zig-zag' },
    ],
  },
  {
    id: 'turn',
    label: 'A wide U-turn',
    widthCells: 21,
    previews: [{ pose: 'wide_u_turn', role: 'own', label: 'Turning' }],
  },
];


interface ControlProps {
  field: FieldV2;
  /** The object this field's path is relative to: a layer, or the document. */
  scope: Record<string, unknown>;
  /** Literals the document declares, for the colour picker. */
  literals: string[];
  onChange: (path: string, value: unknown) => void;
  onDrop: (path: string) => void;
}

/** One control, chosen by the descriptor rather than by this file. */
const Control: React.FC<ControlProps> = ({ field, scope, literals, onChange, onDrop }) => {
  const { kind } = field;
  const value = read(scope, field.path);

  switch (kind.control) {
    case 'color':
      return (
        <label className="builder-field builder-field-color">
          <span>{field.label}</span>
          <input
            type="color"
            value={typeof value === 'string' ? value : '#000000'}
            onChange={(event) => onChange(field.path, event.target.value)}
          />
          {field.help ? <small>{field.help}</small> : null}
        </label>
      );

    case 'colorRef': {
      const reference = (value ?? {}) as Record<string, unknown>;
      const current =
        typeof reference.literal === 'string'
          ? `literal:${reference.literal}`
          : `slot:${String(reference.slot ?? 'fill')}`;
      return (
        <label className="builder-field">
          <span>{field.label}</span>
          <select
            value={current}
            onChange={(event) => {
              const [tag, name] = event.target.value.split(':');
              // Replace the whole reference rather than patching a key: a
              // reference carrying both `slot` and `literal` is not a thing
              // the schema can read, and patching leaves the old key behind.
              onChange(field.path, {
                ...(tag === 'slot' ? { slot: name } : { literal: name }),
                ...(reference.lighten !== undefined
                  ? { lighten: reference.lighten }
                  : {}),
              });
            }}
          >
            <optgroup label="Palette">
              {kind.slots.map((slot) => (
                <option key={slot.value} value={`slot:${slot.value}`}>
                  {slot.label}
                </option>
              ))}
            </optgroup>
            {literals.length > 0 ? (
              <optgroup label="Your colours">
                {literals.map((name) => (
                  <option key={name} value={`literal:${name}`}>
                    {name}
                  </option>
                ))}
              </optgroup>
            ) : null}
          </select>
          {field.help ? <small>{field.help}</small> : null}
        </label>
      );
    }

    case 'text':
      return (
        <label className="builder-field">
          <span>{field.label}</span>
          <input
            type="text"
            maxLength={kind.maxLength}
            value={typeof value === 'string' ? value : ''}
            onChange={(event) => {
              const next = kind.charset
                ? event.target.value
                    .toUpperCase()
                    .split('')
                    .filter((letter) => kind.charset?.includes(letter))
                    .join('')
                : event.target.value;
              onChange(field.path, next);
            }}
          />
          {field.help ? <small>{field.help}</small> : null}
        </label>
      );

    case 'toggle':
      return (
        <label className="builder-field builder-field-toggle">
          <input
            type="checkbox"
            checked={value === true}
            onChange={(event) => onChange(field.path, event.target.checked)}
          />
          <span>{field.label}</span>
          {field.help ? <small>{field.help}</small> : null}
        </label>
      );

    case 'number':
      return (
        <label className="builder-field">
          <span>{field.label}</span>
          <input
            type="range"
            min={kind.min}
            max={kind.max}
            step={kind.step}
            value={asConstant(value) ?? kind.min}
            onChange={(event) => onChange(field.path, Number(event.target.value))}
          />
          <output>{asConstant(value) ?? kind.min}</output>
          {field.help ? <small>{field.help}</small> : null}
        </label>
      );

    case 'expression':
      return (
        <ExpressionField
          field={field}
          kind={kind}
          value={value}
          onChange={onChange}
        />
      );

    case 'choice':
      return (
        <label className="builder-field">
          <span>{field.label}</span>
          <select
            value={typeof value === 'string' ? value : kind.options[0]?.value}
            onChange={(event) => onChange(field.path, event.target.value)}
          >
            {kind.options.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
          {kind.options.find((option) => option.value === value)?.help ? (
            <small>{kind.options.find((option) => option.value === value)?.help}</small>
          ) : field.help ? (
            <small>{field.help}</small>
          ) : null}
        </label>
      );

    case 'group':
      return (
        <fieldset className="builder-group">
          <legend>{field.label}</legend>
          {kind.children.map((child) => (
            <Control
              key={child.path}
              field={child}
              scope={scope}
              literals={literals}
              onChange={onChange}
              onDrop={onDrop}
            />
          ))}
        </fieldset>
      );

    case 'optional': {
      const present = value !== undefined && value !== null;
      return (
        <fieldset className="builder-group">
          <legend>
            <label className="builder-field-toggle">
              <input
                type="checkbox"
                checked={present}
                onChange={(event) => {
                  if (event.target.checked) {
                    // The descriptor supplies what "on" inserts, so switching
                    // a section on can never hand back a validation error.
                    onChange(field.path, field.default);
                  } else {
                    onDrop(field.path);
                  }
                }}
              />
              <span>{field.label}</span>
            </label>
          </legend>
          {present
            ? kind.children.map((child) => (
                <Control
                  key={child.path}
                  field={child}
                  scope={scope}
                  literals={literals}
                  onChange={onChange}
                  onDrop={onDrop}
                />
              ))
            : null}
          {field.help ? <small className="builder-note">{field.help}</small> : null}
        </fieldset>
      );
    }

    case 'list': {
      const items = Array.isArray(value) ? value : [];
      return (
        <fieldset className="builder-group">
          <legend>{field.label}</legend>
          {items.map((item, index) => (
            <div className="builder-list-item" key={`${field.path}-${index}`}>
              <div className="builder-list-head">
                <strong>{`${kind.itemLabel} ${index + 1}`}</strong>
                <button
                  type="button"
                  className="builder-icon-button"
                  disabled={items.length <= kind.minItems}
                  onClick={() =>
                    onChange(
                      field.path,
                      items.filter((_, other) => other !== index),
                    )
                  }
                  aria-label={`Remove ${kind.itemLabel} ${index + 1}`}
                >
                  ✕
                </button>
              </div>
              {kind.children.map((child) => (
                <Control
                  key={`${field.path}.${index}.${child.path}`}
                  field={{ ...child, path: child.path }}
                  scope={item as Record<string, unknown>}
                  literals={literals}
                  onChange={(path, next) =>
                    onChange(
                      field.path,
                      items.map((existing, other) =>
                        other === index ? write(existing, path, next) : existing,
                      ),
                    )
                  }
                  onDrop={(path) =>
                    onChange(
                      field.path,
                      items.map((existing, other) =>
                        other === index ? drop(existing, path) : existing,
                      ),
                    )
                  }
                />
              ))}
            </div>
          ))}
          <button
            type="button"
            className="game-shell-button is-small"
            disabled={items.length >= kind.maxItems}
            onClick={() => onChange(field.path, [...items, kind.itemDefault])}
          >
            {`Add ${kind.itemLabel.toLowerCase()}`}
          </button>
        </fieldset>
      );
    }

    case 'variant': {
      // The variant's tag lives inside whatever the field's path points at —
      // at the scope root for a layer's kind, one level down for a source.
      const container =
        field.path === kind.tag
          ? scope
          : ((read(scope, field.path) ?? {}) as Record<string, unknown>);
      const tagPath = field.path === kind.tag ? kind.tag : `${field.path}.${kind.tag}`;
      const current = String(container[kind.tag] ?? kind.options[0]?.value);
      const option = kind.options.find((choice) => choice.value === current);

      return (
        <fieldset className="builder-group">
          <legend>{field.label}</legend>
          <label className="builder-field">
            <span>Type</span>
            <select
              value={current}
              onChange={(event) => {
                const next = kind.options.find(
                  (choice) => choice.value === event.target.value,
                );
                if (!next) {
                  return;
                }
                // Replace wholesale with the descriptor's validating default.
                // Patching the tag alone would leave the previous variant's
                // fields behind, and `deny_unknown_fields` would refuse the
                // result with a message about a key the author never typed.
                if (field.path === kind.tag) {
                  onChange('', next.default);
                } else {
                  onChange(field.path, next.default);
                }
              }}
            >
              {kind.options.map((choice) => (
                <option key={choice.value} value={choice.value}>
                  {choice.label}
                </option>
              ))}
            </select>
            {option?.help ? <small>{option.help}</small> : null}
          </label>
          {option?.children.map((child) => (
            <Control
              key={child.path}
              field={child}
              scope={scope}
              literals={literals}
              onChange={onChange}
              onDrop={onDrop}
            />
          ))}
        </fieldset>
      );
    }

    default: {
      // Exhaustiveness: a control the Rust descriptor can emit and this file
      // cannot render is a type error, not a blank space in the panel.
      const unhandled: never = kind;
      return <p className="builder-note">{`Unsupported control: ${JSON.stringify(unhandled)}`}</p>;
    }
  }
};

interface ExpressionFieldProps {
  field: FieldV2;
  kind: Extract<KindV2, { control: 'expression' }>;
  value: unknown;
  onChange: (path: string, value: unknown) => void;
}

/**
 * A number that can become an expression, and back.
 *
 * The slider and the fx box are one value in two views, which is what makes
 * "animation is not a separate thing" true in the interface and not only in the
 * schema. Flipping to fx pre-fills the current constant, so an author starts
 * from what they had rather than from an empty box; flipping back is offered
 * only when the expression is still a plain number, because silently discarding
 * someone's arithmetic would be worse than leaving the toggle disabled.
 */
const ExpressionField: React.FC<ExpressionFieldProps> = ({ field, kind, value, onChange }) => {
  const constant = asConstant(value);
  const [showFx, setShowFx] = useState(constant === null);

  useEffect(() => {
    if (constant === null) {
      setShowFx(true);
    }
  }, [constant]);

  return (
    <div className="builder-field builder-field-expression">
      <div className="builder-field-head">
        <span>{field.label}</span>
        <span className="builder-site" title={`Worked out ${kind.siteLabel}`}>
          {kind.siteLabel}
        </span>
        <button
          type="button"
          className={`builder-fx${showFx ? ' is-on' : ''}`}
          aria-pressed={showFx}
          onClick={() => {
            if (showFx && constant !== null) {
              setShowFx(false);
              onChange(field.path, constant);
              return;
            }
            setShowFx(true);
            onChange(field.path, String(constant ?? kind.min));
          }}
          title={
            showFx
              ? constant === null
                ? 'Simplify this to a number first to go back to the slider'
                : 'Back to a slider'
              : 'Write this as an expression'
          }
          disabled={showFx && constant === null}
        >
          fx
        </button>
      </div>

      {showFx ? (
        <>
          <input
            type="text"
            className="builder-expression-input"
            value={typeof value === 'string' ? value : String(constant ?? '')}
            spellCheck={false}
            onChange={(event) => onChange(field.path, event.target.value)}
          />
          <small>
            {`May use ${kind.inputs.map((input) => `\`${input}\``).join(', ')}.`}
          </small>
        </>
      ) : (
        <>
          <input
            type="range"
            min={kind.min}
            max={kind.max}
            step={kind.step}
            value={constant ?? kind.min}
            onChange={(event) => onChange(field.path, Number(event.target.value))}
          />
          <output>{constant ?? kind.min}</output>
        </>
      )}
      {field.help ? <small>{field.help}</small> : null}
    </div>
  );
};

const SkinBuilder: React.FC<SkinBuilderProps> = ({ onOpenAuth, onOpenAccount }) => {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const { skinId } = useParams<{ skinId: string }>();

  const [schema, setSchema] = useState<SchemaV2 | null>(null);
  const [templates, setTemplates] = useState<Template[]>([]);
  const [document, setDocument] = useState<Document | null>(null);
  const [selected, setSelected] = useState(0);
  const [problems, setProblems] = useState<string[]>([]);
  /**
   * Whether a save has been turned away for want of a name.
   *
   * The document is invalid without one from the first keystroke, but saying
   * so from the first keystroke is scolding somebody for not having finished
   * yet. The rule only becomes news at the moment it stops you.
   */
  const [nameRefused, setNameRefused] = useState(false);
  const [generating, setGenerating] = useState(false);
  const nameRef = useRef<HTMLInputElement | null>(null);
  const [status, setStatus] = useState<string | null>(null);
  const [cost, setCost] = useState<Cost | null>(null);
  const [skin, setSkin] = useState<SkinSummary | null>(null);
  const [saving, setSaving] = useState(false);
  const [revision, setRevision] = useState(0);
  const [dragging, setDragging] = useState<number | null>(null);
  /** Opacities parked by the eye toggle, so hiding is reversible. */
  const hidden = useRef<Record<number, unknown>>({});

  const handle = useMemo(() => `draft:${skinId ?? 'new'}`, [skinId]);
  const valid = problems.length === 0;
  // The schema owns the limit; reading it here keeps the field and the
  // validator from disagreeing about what a too-long name is.
  const nameLimit = useMemo(() => {
    const field = schema?.document.find((each) => each.path === 'name');
    return field?.kind.control === 'text' ? field.kind.maxLength : 48;
  }, [schema]);

  useEffect(() => {
    let cancelled = false;
    void initWasm().then(() => {
      const wasm = getWasm();
      if (cancelled || !wasm) {
        return;
      }
      try {
        setSchema(JSON.parse(wasm.skinSchemaV2()) as SchemaV2);
        setTemplates(JSON.parse(wasm.skinTemplatesV2()) as Template[]);
      } catch (cause) {
        setProblems([`The editor could not read the skin format: ${String(cause)}`]);
      }
    });
    return () => {
      cancelled = true;
    };
  }, []);

  // Load an existing skin, converting it if it was written in the older
  // format. A v1 skin is not a second-class citizen here — it is the same
  // skin, described the way this editor describes things.
  useEffect(() => {
    if (!skinId || !schema) {
      return;
    }
    let cancelled = false;
    void (async () => {
      try {
        const mine = await api.browseAuthoredSkins('snake', 'mine');
        const found = mine.skins.find((entry) => String(entry.skinId) === skinId);
        if (cancelled || !found) {
          if (!found) {
            setProblems(['That skin is not one of yours, or no longer exists.']);
          }
          return;
        }
        setSkin(found);
        if (!found.contentRef) {
          setProblems(['That skin has no revision to open.']);
          return;
        }
        const stored = await api.getSkinDocument(found.contentRef);
        if (cancelled) {
          return;
        }
        const wasm = getWasm();
        // Converted on the way in, so a skin written in the older format opens
        // as the same skin described the way this editor describes things —
        // not as a second-class citizen with half its controls missing.
        setDocument(
          (wasm
            ? JSON.parse(wasm.upgradeSkinDocument(JSON.stringify(stored)))
            : stored) as Document,
        );
      } catch (cause) {
        setProblems([isApiError(cause) ? cause.message : String(cause)]);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [schema, skinId]);

  // Recompile on every settled edit. Compilation runs the same validator the
  // server runs, so the preview and the save agree about what is valid.
  useEffect(() => {
    const wasm = getWasm();
    if (!wasm || !document) {
      return;
    }
    // The validator wants a display name and is right to; a draft nobody has
    // named yet is not a bug, it is a draft. It previews under a stand-in so
    // the missing name is the save's business rather than the renderer's, and
    // so one blank field cannot blank the whole page.
    const named = String(document.name ?? '').trim()
      ? document
      : { ...document, name: 'Untitled skin' };
    const json = JSON.stringify(named);
    try {
      setCost(JSON.parse(wasm.skinCostV2(json)) as Cost);
    } catch {
      setCost(null);
    }
    try {
      wasm.registerDraftSkin(handle, json);
      setProblems([]);
      setRevision((current) => current + 1);
    } catch (cause) {
      setProblems(String(cause).split('\n').filter(Boolean));
    }
  }, [document, handle]);

  const unnamed = !String(document?.name ?? '').trim();
  const shownProblems = useMemo(
    () =>
      nameRefused && unnamed ? [...problems, 'name — a skin needs a display name'] : problems,
    [problems, nameRefused, unnamed],
  );

  const layers = useMemo(
    () => (Array.isArray(document?.layers) ? (document.layers as Layer[]) : []),
    [document],
  );
  const literals = useMemo(
    () => Object.keys((document?.literals ?? {}) as Record<string, string>),
    [document],
  );

  const changeDocument = useCallback((path: string, value: unknown) => {
    setDocument((current) => (current ? (write(current, path, value) as Document) : current));
    setStatus(null);
  }, []);

  const changeLayer = useCallback(
    (index: number, path: string, value: unknown) => {
      setDocument((current) => {
        if (!current) {
          return current;
        }
        const list = (current.layers as Layer[]) ?? [];
        return {
          ...current,
          layers: list.map((layer, other) =>
            other === index
              ? // An empty path replaces the layer wholesale, which is what a
                // kind switch does: the new kind's fields are not the old
                // kind's, and the name is the one thing worth carrying over.
                path === ''
                ? { ...(value as Layer), name: layer.name }
                : (write(layer, path, value) as Layer)
              : layer,
          ),
        };
      });
      setStatus(null);
    },
    [],
  );

  const dropLayerPath = useCallback(
    (index: number, path: string) => {
      setDocument((current) => {
        if (!current) {
          return current;
        }
        const list = (current.layers as Layer[]) ?? [];
        return {
          ...current,
          layers: list.map((layer, other) =>
            other === index ? (drop(layer, path) as Layer) : layer,
          ),
        };
      });
    },
    [],
  );

  const addLayer = useCallback(
    (variant: Variant) => {
      setDocument((current) => {
        if (!current) {
          return current;
        }
        const list = (current.layers as Layer[]) ?? [];
        return { ...current, layers: [...list, { ...variant.default }] };
      });
      setSelected(layers.length);
      setStatus(null);
    },
    [layers.length],
  );

  const removeLayer = useCallback((index: number) => {
    setDocument((current) => {
      if (!current) {
        return current;
      }
      const list = (current.layers as Layer[]) ?? [];
      return { ...current, layers: list.filter((_, other) => other !== index) };
    });
    setSelected((current) => Math.max(0, current > index ? current - 1 : current));
  }, []);

  /** Move a layer within the stack. `from` and `to` are document indices. */
  const moveLayer = useCallback((from: number, to: number) => {
    setDocument((current) => {
      if (!current || from === to) {
        return current;
      }
      const list = [...((current.layers as Layer[]) ?? [])];
      const [moved] = list.splice(from, 1);
      list.splice(to, 0, moved);
      return { ...current, layers: list };
    });
    setSelected(to);
  }, []);

  const toggleHidden = useCallback(
    (index: number) => {
      const layer = layers[index];
      if (!layer) {
        return;
      }
      const isHidden = asConstant(layer.opacity) === 0;
      if (isHidden) {
        changeLayer(index, 'opacity', hidden.current[index] ?? 1);
        delete hidden.current[index];
      } else {
        hidden.current[index] = layer.opacity;
        changeLayer(index, 'opacity', 0);
      }
    },
    [changeLayer, layers],
  );

  const save = useCallback(async () => {
    if (!user) {
      onOpenAuth();
      return;
    }
    if (!document) {
      return;
    }
    if (!String(document.name ?? '').trim()) {
      setNameRefused(true);
      nameRef.current?.focus();
      return;
    }
    setSaving(true);
    setStatus(null);
    try {
      const name = String(document.name).trim();
      if (skin) {
        setSkin(await api.updateSkin(skin.skinId, { name, document }));
        setStatus('Saved.');
      } else {
        const created = await api.createSkin({ name, document });
        setSkin(created);
        setStatus('Saved.');
        navigate(`/skins/builder/${created.skinId}`, { replace: true });
      }
    } catch (cause) {
      setProblems([isApiError(cause) ? cause.message : String(cause)]);
    } finally {
      setSaving(false);
    }
  }, [document, navigate, onOpenAuth, skin, user]);

  const requestReview = useCallback(async () => {
    if (!skin) {
      return;
    }
    try {
      await api.requestSkinPublication(skin.skinId);
      setStatus('Sent for review.');
    } catch (cause) {
      setProblems([isApiError(cause) ? cause.message : String(cause)]);
    }
  }, [skin]);

  const chrome = (
    <HomeHeader
      activePage="skins"
      currentUser={user}
      lobbyMembers={[]}
      hasLobby={false}
      onInvite={() => {}}
      onJoinGame={() => {}}
      onLeaveLobby={() => {}}
      onAuthClick={onOpenAuth}
      onOpenAccount={onOpenAccount}
      onLogout={logout}
    />
  );

  // A new skin picks a starting point first. An empty stack is not a skin, and
  // the first thing an author should see is something that already paints.
  if (!document) {
    return (
      <div className="home-page builder-page">
        {chrome}
        <main className="builder-main">
          <div className="builder-intro">
            <h1 className="builder-title">Skin Builder</h1>
            <p className="builder-subtitle">
              Start from one of these templates. Mix and match images and effects.
            </p>
          </div>
          <div className="builder-templates">
            {templates.map((template) => (
              <button
                type="button"
                key={template.id}
                className="builder-template"
                onClick={() => setDocument({ ...template.document, name: '' })}
              >
                <strong>{template.label}</strong>
                {/* The skin itself, painted by the real renderer and moving,
                    because what separates these three is what they *do*. A
                    sentence describing a travelling shine is a worse
                    description of a travelling shine than the shine. */}
                <TemplatePreview template={template} />
              </button>
            ))}
          </div>
          {problems.length > 0 ? (
            <ul className="builder-problems" role="alert">
              {problems.map((problem) => (
                <li key={problem}>{problem}</li>
              ))}
            </ul>
          ) : null}
        </main>
      </div>
    );
  }

  const current = layers[selected];
  const overBudget = cost ? cost.ops > cost.maxOps : false;

  return (
    <div className="home-page builder-page">
      {chrome}

      <main className="builder-main">
        {/* Always the page's own name. Titling it after the template just
            chosen made the page look like it belonged to that template, and
            the name is editable in the field above the preview. */}
        <div className="builder-intro">
          <h1 className="builder-title">Skin Builder</h1>
          <button
            type="button"
            className="game-shell-button builder-generate"
            onClick={() => setGenerating(true)}
          >
            <span className="builder-generate-icon" aria-hidden="true">
              <svg viewBox="0 0 24 24" width="15" height="15" fill="currentColor">
                {/* A four-pointed sparkle and two smaller ones: a wand needs a
                    hand to hold it, and this reads at 15px where a wand does
                    not. */}
                <path d="M12 2.6l1.7 4.6 4.6 1.7-4.6 1.7L12 15.2l-1.7-4.6L5.7 8.9l4.6-1.7z" />
                <path d="M18.4 14.1l.85 2.3 2.3.85-2.3.85-.85 2.3-.85-2.3-2.3-.85 2.3-.85z" />
                <path d="M5.2 15.4l.6 1.6 1.6.6-1.6.6-.6 1.6-.6-1.6-1.6-.6 1.6-.6z" />
              </svg>
            </span>
            Generate
          </button>
        </div>

        {shownProblems.length > 0 ? (
          <ul className="builder-problems" role="alert">
            {shownProblems.map((problem) => (
              <li key={problem}>{problem}</li>
            ))}
          </ul>
        ) : null}

        {status ? (
          <p className="builder-status" role="status">
            {status}
          </p>
        ) : null}

        <div className="builder-workbench">
          {/* Preview and layers ride together in a column that sticks to the
              viewport, because both are things you consult *while* editing a
              field in the pane beside them. A preview you have to scroll back
              up to is not a preview of what you are currently doing. */}
          <div className="builder-sidebar">
            {/* The skin's name, in the same field the front page asks for a
                nickname in. It is the one property of the document that is not
                a rendering choice, so it sits above the picture rather than
                filed under Skin settings with the cycle length. No label: a
                placeholder says the same thing and takes no room from a column
                this narrow. */}
            <input
              ref={nameRef}
              type="text"
              className="w-full bg-white px-4 py-3 text-base border-2 border-gray-300 rounded-lg transition-colors focus:outline-none focus:border-blue-500"
              value={String(document.name ?? '')}
              onChange={(event) => {
                setNameRefused(false);
                changeDocument('name', event.target.value);
              }}
              placeholder="Skin name"
              maxLength={nameLimit}
              aria-label="Skin name"
            />

            <PreviewDeck handle={handle} revision={revision} valid={valid} />

            <aside className="builder-stack" aria-label="Layers">
            <h2 className="builder-panel-title">Layers</h2>

            {schema?.systemLayers
              .filter((system) => system.position === 'top')
              .map((system) => (
                <SystemRow key={system.name} name={system.name} help={system.help} />
              ))}

            {/* Reversed: the last layer painted sits on top of everything, so
                it belongs at the top of the list. Showing them in document
                order would put the topmost thing at the bottom. */}
            {[...layers]
              .map((layer, index) => ({ layer, index }))
              .reverse()
              .map(({ layer, index }) => (
                <div
                  key={index}
                  className={`builder-layer-row${index === selected ? ' is-selected' : ''}${
                    dragging === index ? ' is-dragging' : ''
                  }`}
                  draggable
                  onDragStart={() => setDragging(index)}
                  onDragEnd={() => setDragging(null)}
                  onDragOver={(event) => event.preventDefault()}
                  onDrop={(event) => {
                    event.preventDefault();
                    if (dragging !== null) {
                      moveLayer(dragging, index);
                    }
                    setDragging(null);
                  }}
                >
                  <button
                    type="button"
                    className="builder-eye"
                    aria-pressed={asConstant(layer.opacity) !== 0}
                    aria-label={
                      asConstant(layer.opacity) === 0 ? 'Show layer' : 'Hide layer'
                    }
                    onClick={() => toggleHidden(index)}
                  >
                    {asConstant(layer.opacity) === 0 ? '○' : '●'}
                  </button>
                  <button
                    type="button"
                    className="builder-layer-name"
                    onClick={() => setSelected(index)}
                  >
                    <strong>{String(layer.name ?? 'Layer')}</strong>
                    <span>{String(layer.type ?? '')}</span>
                  </button>
                  <button
                    type="button"
                    className="builder-icon-button"
                    aria-label={`Delete ${String(layer.name ?? 'layer')}`}
                    onClick={() => removeLayer(index)}
                  >
                    ✕
                  </button>
                </div>
              ))}

            {schema?.systemLayers
              .filter((system) => system.position === 'bottom')
              .map((system) => (
                <SystemRow key={system.name} name={system.name} help={system.help} />
              ))}

            <div className="builder-add">
              {schema?.addLayer.map((variant) => (
                <button
                  type="button"
                  key={variant.value}
                  className="game-shell-button is-small"
                  title={variant.help}
                  disabled={cost ? cost.layers >= cost.maxLayers : false}
                  onClick={() => addLayer(variant)}
                >
                  {`+ ${variant.label}`}
                </button>
              ))}
              </div>
            </aside>
          </div>

          <section className="builder-inspector" aria-label="Layer settings">
            <h2 className="builder-panel-title">
              {current ? String(current.name ?? 'Layer') : 'Nothing selected'}
            </h2>
            {current && schema ? (
              <form onSubmit={(event) => event.preventDefault()}>
                {schema.layer.map((field) => (
                  <Control
                    key={field.path}
                    field={field}
                    scope={current}
                    literals={literals}
                    onChange={(path, value) => changeLayer(selected, path, value)}
                    onDrop={(path) => dropLayerPath(selected, path)}
                  />
                ))}
              </form>
            ) : (
              <p className="builder-note">
                Pick a layer on the left, or add one.
              </p>
            )}
          </section>
        </div>

        <details className="builder-document">
          <summary>Skin settings</summary>
          {schema ? (
            <form onSubmit={(event) => event.preventDefault()}>
              {schema.document
                .filter((field) => field.path !== 'name')
                .map((field) => (
                  <Control
                    key={field.path}
                    field={field}
                    scope={document}
                    literals={literals}
                    onChange={changeDocument}
                    onDrop={(path) =>
                      setDocument((held) => (held ? (drop(held, path) as Document) : held))
                    }
                  />
                ))}
            </form>
          ) : null}
        </details>
      </main>

      {generating ? (
        <GenerateSkinModal
          onClose={() => setGenerating(false)}
          onUse={(generated, name) => {
            // The generator hands over a document that has already passed the
            // validator, so this is the same move as picking a template — with
            // a name, which a template deliberately does not bring.
            setDocument({ ...(generated as Document), name });
            setNameRefused(false);
            setSelected(0);
            setGenerating(false);
          }}
        />
      ) : null}

      {/* Pinned to the viewport rather than sitting at the end of the page.
          The stack is long and the inspector is longer, so a Save that lives
          at the bottom of the document is a Save you have to go looking for —
          and the cost meter beside it is only useful while you are spending. */}
      <div className="builder-cta">
        <button
          type="button"
          className="game-shell-button"
          onClick={() => navigate('/skins')}
        >
          Back
        </button>

        <div className="builder-cta-meta">
          {status ? (
            <p className="builder-status" role="status">
              {status}
            </p>
          ) : null}
          {cost ? (
            <p className={`builder-cost${overBudget ? ' is-over' : ''}`}>
              <span>{`${cost.ops}/${cost.maxOps} draw ops`}</span>
              <span>{`${cost.layers}/${cost.maxLayers} layers`}</span>
            </p>
          ) : null}
        </div>

        <div className="builder-cta-actions">
          {skin ? (
            <button
              type="button"
              className="game-shell-button"
              onClick={() => void requestReview()}
              disabled={problems.length > 0}
            >
              Send for review
            </button>
          ) : null}
          <button
            type="button"
            className="game-shell-button is-primary"
            onClick={() => void save()}
            disabled={saving}
          >
            {skin ? 'Save revision' : 'Save skin'}
          </button>
        </div>
      </div>
    </div>
  );
};

/**
 * One template, painted by the renderer that will paint the real thing.
 *
 * Registered as a draft under its own handle rather than described in a
 * caption: these three differ in how they *move*, and a still swatch or a
 * sentence about a travelling shine is a poor account of one.
 */
const TemplatePreview: React.FC<{ template: Template }> = ({ template }) => {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const handle = `draft:template-${template.id}`;
  const [layout, setLayout] = useState({
    canvasWidth: 320,
    canvasHeight: 110,
    cropWidth: 320,
    cropHeight: 44,
    offsetX: 0,
    offsetY: 56,
  });

  useEffect(() => {
    const wasm = getWasm();
    if (!wasm) {
      return;
    }
    try {
      wasm.registerDraftSkin(handle, JSON.stringify(template.document));
      const bounds = JSON.parse(
        wasm.skinFixtureBounds(handle, TEMPLATE_POSE, TEMPLATE_CELL, false),
      ) as { x: number; y: number; width: number; height: number };
      setLayout({
        canvasWidth: Math.ceil(bounds.x + bounds.width + PREVIEW_PAD),
        canvasHeight: Math.ceil(bounds.y + bounds.height + PREVIEW_PAD),
        cropWidth: Math.ceil(bounds.width + PREVIEW_PAD * 2),
        cropHeight: Math.ceil(bounds.height + PREVIEW_PAD * 2),
        offsetX: Math.round(bounds.x - PREVIEW_PAD),
        offsetY: Math.round(bounds.y - PREVIEW_PAD),
      });
    } catch {
      // A template that will not compile is a bug caught by its own test, not
      // something to break the picker over.
    }
  }, [handle, template.document]);

  useEffect(() => {
    const canvas = canvasRef.current;
    const wasm = getWasm();
    if (!canvas || !wasm) {
      return;
    }
    let frame = requestAnimationFrame(function loop(now: number) {
      try {
        wasm.renderSkinFixture(
          canvas,
          handle,
          TEMPLATE_POSE,
          template.previewRole,
          TEMPLATE_CELL,
          false,
          false,
          now,
          false,
        );
      } catch {
        // Leave the last good frame up.
      }
      frame = requestAnimationFrame(loop);
    });
    return () => cancelAnimationFrame(frame);
  }, [handle, template.previewRole, layout.canvasWidth, layout.canvasHeight]);

  return (
    <span
      className="builder-template-preview"
      style={{ height: layout.cropHeight }}
      aria-hidden="true"
    >
      <canvas
        ref={canvasRef}
        width={layout.canvasWidth}
        height={layout.canvasHeight}
        style={{ marginLeft: -layout.offsetX, marginTop: -layout.offsetY }}
      />
    </span>
  );
};

/** A layer the engine owns, shown so the stacking the panel draws is real. */
const SystemRow: React.FC<{ name: string; help: string }> = ({ name, help }) => (
  <div className="builder-layer-row is-system" title={help}>
    <span className="builder-eye is-locked" aria-hidden="true">
      🔒
    </span>
    <span className="builder-layer-name">
      <strong>{name}</strong>
      <span>always on</span>
    </span>
  </div>
);

interface BuilderPreviewProps {
  handle: string;
  pose: string;
  role: string;
  /** Never drawn. The canvas is a picture, so this is its accessible name. */
  label: string;
  revision: number;
  valid: boolean;
  /** Cell size in pixels. Each slide picks one that fits the panel. */
  cell: number;
}

/**
 * One preview pose, always animating.
 *
 * A builder needs to see motion — a skin frozen at one frame hides half of what
 * an animation does — so unlike the browse page these never stop.
 *
 * It sizes itself to its own pose and nothing else. Slides arrange them, and a
 * slide knows what it is arranging; making every picture share one box was
 * only ever needed to hold a row of captions level, and there are no captions.
 */
const BuilderPreview: React.FC<BuilderPreviewProps> = ({
  handle,
  pose,
  role,
  label,
  revision,
  valid,
  cell,
}) => {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [layout, setLayout] = useState({
    canvasWidth: 300,
    canvasHeight: 120,
    cropWidth: 300,
    cropHeight: 40,
    offsetX: 0,
    offsetY: 50,
  });

  // Fixture poses paint at their own arena coordinates rather than at the
  // origin, so the canvas has to be tall enough to reach the pose and the
  // wrapper crops back to it. Without this a slide is mostly empty space.
  useEffect(() => {
    const wasm = getWasm();
    if (!wasm || !valid) {
      return;
    }
    try {
      const bounds = JSON.parse(wasm.skinFixtureBounds(handle, pose, cell, false)) as {
        x: number;
        y: number;
        width: number;
        height: number;
      };
      setLayout({
        canvasWidth: Math.ceil(bounds.x + bounds.width + PREVIEW_PAD),
        canvasHeight: Math.ceil(bounds.y + bounds.height + PREVIEW_PAD),
        cropWidth: Math.ceil(bounds.width + PREVIEW_PAD * 2),
        cropHeight: Math.ceil(bounds.height + PREVIEW_PAD * 2),
        offsetX: Math.round(bounds.x - PREVIEW_PAD),
        offsetY: Math.round(bounds.y - PREVIEW_PAD),
      });
    } catch {
      // Keep the previous framing; a slightly wrong one beats none.
    }
  }, [handle, pose, cell, revision, valid]);

  useEffect(() => {
    const canvas = canvasRef.current;
    const wasm = getWasm();
    if (!canvas || !wasm || !valid) {
      return;
    }
    let frame = requestAnimationFrame(function loop(now: number) {
      try {
        wasm.renderSkinFixture(canvas, handle, pose, role, cell, false, false, now, false);
      } catch {
        // An invalid draft leaves the last good frame up; the problem list
        // beside it is what says why.
      }
      frame = requestAnimationFrame(loop);
    });
    return () => cancelAnimationFrame(frame);
  }, [handle, pose, role, cell, revision, valid, layout.canvasWidth, layout.canvasHeight]);

  return (
    <span
      className="builder-preview-crop"
      style={{ width: layout.cropWidth, height: layout.cropHeight }}
    >
      <canvas
        ref={canvasRef}
        width={layout.canvasWidth}
        height={layout.canvasHeight}
        style={{ marginLeft: -layout.offsetX, marginTop: -layout.offsetY }}
        role="img"
        aria-label={label}
      />
    </span>
  );
};

/**
 * The preview panel: one slide at a time, with a chevron on each side.
 *
 * Nothing here is labelled. The pictures are the content, and a caption under
 * each one would be a word competing with the thing it describes for the
 * narrowest column on the page.
 */
const PreviewDeck: React.FC<{ handle: string; revision: number; valid: boolean }> = ({
  handle,
  revision,
  valid,
}) => {
  const [index, setIndex] = useState(0);
  const [width, setWidth] = useState(0);
  const slideRef = useRef<HTMLDivElement | null>(null);
  const slide = SLIDES[index];
  const step = (delta: number) => setIndex((at) => (at + delta + SLIDES.length) % SLIDES.length);

  // The panel is whatever the sidebar column gives it, and that changes with
  // the viewport, so the drawing size is measured rather than assumed.
  useEffect(() => {
    const node = slideRef.current;
    if (!node || typeof ResizeObserver === 'undefined') {
      return;
    }
    const observer = new ResizeObserver(([entry]) => setWidth(entry.contentRect.width));
    observer.observe(node);
    return () => observer.disconnect();
  }, []);

  // Floors keep the drawing inside the box; the clamp keeps it legible at one
  // end and stops it outgrowing the panel's height at the other.
  const cell = width
    ? Math.max(
        6,
        Math.min(15, Math.floor((width - PREVIEW_PAD * 2 - 2) / slide.widthCells)),
      )
    : 10;

  return (
    <section className="builder-preview-panel" aria-label="Preview">
      <h2 className="builder-panel-title">Preview</h2>
      <div className="builder-deck">
        <button
          type="button"
          className="builder-chevron is-prev"
          aria-label="Previous preview"
          onClick={() => step(-1)}
        >
          ‹
        </button>
        <div
          ref={slideRef}
          className={`builder-slide is-${slide.id}`}
          role="group"
          aria-label={slide.label}
        >
          {slide.previews.map((preview) => (
            <BuilderPreview
              key={`${preview.pose}-${preview.role}`}
              handle={handle}
              pose={preview.pose}
              role={preview.role}
              label={preview.label}
              revision={revision}
              valid={valid}
              cell={cell}
            />
          ))}
        </div>
        <button
          type="button"
          className="builder-chevron is-next"
          aria-label="Next preview"
          onClick={() => step(1)}
        >
          ›
        </button>
      </div>
      <div className="builder-dots" aria-hidden="true">
        {SLIDES.map((each, at) => (
          <span key={each.id} className={at === index ? 'is-on' : undefined} />
        ))}
      </div>
    </section>
  );
};



export default SkinBuilder;
