import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import type { AccountModalView } from './AccountModal';
import { HomeHeader } from './HomeHeader';
import { useAuth } from '../contexts/AuthContext';
import { api, isApiError } from '../services/api';
import { getWasm, initWasm } from '../wasm';
import type { SkinSummary } from '../types/generated';

/**
 * The Skin Builder.
 *
 * Every control here is generated by walking a descriptor the Rust crate emits,
 * never hand-written. The descriptor is produced by exhaustive destructuring of
 * the document type, so a field added to a skin breaks the build until it is
 * described — which is what makes "the editor cannot drift from the object
 * model" a guarantee rather than a promise.
 *
 * The corollary is that this file must handle every control kind the descriptor
 * can carry. The `never` assignment at the end of {@link Control} is what
 * enforces that: adding a kind on the Rust side and not here is a type error.
 */

interface SkinBuilderProps {
  onOpenAuth: () => void;
  onOpenAccount: (view: AccountModalView) => void;
}

/** Mirrors `skin_schema::describe::FieldKind`. */
type FieldKind =
  | { control: 'color' }
  | { control: 'number'; min: number; max: number; step: number }
  | { control: 'text'; maxLength: number }
  | { control: 'choice'; options: string[] }
  | { control: 'group'; children: FieldNode[] }
  | { control: 'optional'; children: FieldNode[] }
  | { control: 'list'; itemLabel: string; children: FieldNode[] };

interface FieldNode {
  path: string;
  label: string;
  kind: FieldKind;
  help?: string;
}

type Document = Record<string, unknown>;

/** Read a dotted path out of the document. */
const read = (document: Document, path: string): unknown =>
  path.split('.').reduce<unknown>((value, key) => {
    if (value === null || typeof value !== 'object') {
      return undefined;
    }
    return (value as Record<string, unknown>)[key];
  }, document);

/**
 * Write a dotted path, returning a new document.
 *
 * Copies down the path rather than mutating, so React sees a changed object and
 * the preview's effect actually re-runs.
 */
const write = (document: Document, path: string, next: unknown): Document => {
  const [head, ...rest] = path.split('.');
  if (rest.length === 0) {
    return { ...document, [head]: next };
  }
  const child = document[head];
  const base: Document =
    child !== null && typeof child === 'object' ? { ...(child as Document) } : {};
  return { ...document, [head]: write(base, rest.join('.'), next) };
};

/**
 * The document a brand-new skin starts from.
 *
 * Aurora's palette rather than classic's, because classic's document carries a
 * label-contrast exemption that a new skin does not get: starting from it would
 * open the editor on a document the validator immediately rejects, which is a
 * poor first impression and a confusing one.
 */
const STARTING_DOCUMENT: Document = {
  schema_version: 1,
  id: 'draft@1',
  name: 'My skin',
  palette: {
    friendly: [
      { fill: '#5ad2e0', outline: '#2e8fa0' },
      { fill: '#38b6d6', outline: '#1d7690' },
    ],
    enemy: [
      { fill: '#ff7a59', outline: '#b8452c' },
      { fill: '#f2564e', outline: '#a32f2e' },
    ],
    free_for_all: [
      { fill: '#5ad2e0', outline: '#2e8fa0' },
      { fill: '#ff7a59', outline: '#b8452c' },
      { fill: '#7d8fa8', outline: '#4a586b' },
      { fill: '#f5c04a', outline: '#a3781f' },
    ],
  },
  head: {
    core_ratio: 0.36,
    core_color: '#10203a',
    gradient: { length_cells: 12, max_opacity: 0.34, color: '#eafcff' },
  },
  outline: {
    extra_px: 2,
    // Fixed by the schema, and deliberately absent from the editor: it is how
    // opponents know you are boosting.
    boost_band: { color: '#fff200', extra_px: 6 },
  },
  labels: {},
};

interface ControlProps {
  field: FieldNode;
  document: Document;
  onChange: (path: string, value: unknown) => void;
}

/**
 * One control, chosen by the descriptor rather than by this file.
 *
 * The exhaustive switch is deliberate: a control kind added in Rust and not
 * handled here is a compile error, not a silently missing input.
 */
const Control: React.FC<ControlProps> = ({ field, document, onChange }) => {
  const { kind } = field;

  switch (kind.control) {
    case 'color': {
      const value = (read(document, field.path) as string) ?? '#000000';
      return (
        <label className="builder-field builder-field-color">
          <span>{field.label}</span>
          <input
            type="color"
            value={value}
            onChange={(event) => onChange(field.path, event.target.value)}
            data-testid={`builder-${field.path}`}
          />
          {field.help ? <small>{field.help}</small> : null}
        </label>
      );
    }
    case 'number': {
      const value = (read(document, field.path) as number) ?? kind.min;
      return (
        <label className="builder-field builder-field-number">
          <span>{field.label}</span>
          <span className="builder-number-row">
            <input
              type="range"
              min={kind.min}
              max={kind.max}
              step={kind.step}
              value={value}
              onChange={(event) => onChange(field.path, Number(event.target.value))}
              data-testid={`builder-${field.path}`}
            />
            <output>{value}</output>
          </span>
          {field.help ? <small>{field.help}</small> : null}
        </label>
      );
    }
    case 'text': {
      const value = (read(document, field.path) as string) ?? '';
      return (
        <label className="builder-field">
          <span>{field.label}</span>
          <input
            type="text"
            maxLength={kind.maxLength}
            value={value}
            onChange={(event) => onChange(field.path, event.target.value)}
            data-testid={`builder-${field.path}`}
          />
          {field.help ? <small>{field.help}</small> : null}
        </label>
      );
    }
    case 'choice': {
      const value = (read(document, field.path) as string) ?? kind.options[0];
      return (
        <label className="builder-field">
          <span>{field.label}</span>
          <select
            value={value}
            onChange={(event) => onChange(field.path, event.target.value)}
            data-testid={`builder-${field.path}`}
          >
            {kind.options.map((option) => (
              <option key={option} value={option}>
                {option}
              </option>
            ))}
          </select>
          {field.help ? <small>{field.help}</small> : null}
        </label>
      );
    }
    case 'group': {
      return (
        <fieldset className="builder-group">
          <legend>{field.label}</legend>
          {field.help ? <p className="builder-help">{field.help}</p> : null}
          {kind.children.map((child) => (
            <Control
              key={child.path}
              field={child}
              document={document}
              onChange={onChange}
            />
          ))}
        </fieldset>
      );
    }
    case 'optional': {
      const present = read(document, field.path) !== undefined
        && read(document, field.path) !== null;
      return (
        <fieldset className="builder-group builder-group-optional">
          <legend>
            <label>
              <input
                type="checkbox"
                checked={present}
                onChange={(event) =>
                  onChange(field.path, event.target.checked ? {} : undefined)
                }
                data-testid={`builder-toggle-${field.path}`}
              />
              {field.label}
            </label>
          </legend>
          {field.help ? <p className="builder-help">{field.help}</p> : null}
          {present
            ? kind.children.map((child) => (
                <Control
                  key={child.path}
                  field={child}
                  document={document}
                  onChange={onChange}
                />
              ))
            : null}
        </fieldset>
      );
    }
    case 'list': {
      const items = (read(document, field.path) as unknown[]) ?? [];
      return (
        <fieldset className="builder-group">
          <legend>{field.label}</legend>
          {items.map((_, index) => (
            <div className="builder-list-item" key={`${field.path}.${index}`}>
              <span className="builder-list-label">
                {kind.itemLabel} {index + 1}
              </span>
              {kind.children.map((child) => (
                <Control
                  key={`${field.path}.${index}.${child.path}`}
                  // A list child's descriptor path is relative to its item, so
                  // the index is spliced in here rather than baked into the
                  // descriptor, which does not know how many items there are.
                  field={{ ...child, path: `${field.path}.${index}.${child.path}` }}
                  document={document}
                  onChange={onChange}
                />
              ))}
              <button
                type="button"
                className="game-shell-button"
                onClick={() =>
                  onChange(
                    field.path,
                    items.filter((__, other) => other !== index),
                  )
                }
              >
                Remove
              </button>
            </div>
          ))}
          <button
            type="button"
            className="game-shell-button"
            onClick={() => onChange(field.path, [...items, {}])}
            data-testid={`builder-add-${field.path}`}
          >
            Add {kind.itemLabel.toLowerCase()}
          </button>
        </fieldset>
      );
    }
    default: {
      // Exhaustiveness: a control kind the Rust descriptor can emit and this
      // file does not handle fails to compile here rather than rendering
      // nothing at runtime.
      const unhandled: never = kind;
      throw new Error(`unhandled control kind: ${JSON.stringify(unhandled)}`);
    }
  }
};

/** The poses a builder needs to see: the main one, plus what catches mistakes. */
const PREVIEW_CELL = 16;
/** Breathing room around the painted snake, so a contour is never clipped. */
const PREVIEW_PAD = 10;

const PREVIEW_POSES: Array<{ pose: string; role: string; label: string }> = [
  { pose: 'longer_than_head_gradient', role: 'own', label: 'Yours' },
  { pose: 'longer_than_head_gradient', role: 'enemy', label: 'As an opponent' },
  { pose: 'single_corner', role: 'own', label: 'Turning' },
];

const SkinBuilder: React.FC<SkinBuilderProps> = ({ onOpenAuth, onOpenAccount }) => {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const { skinId } = useParams();

  const [schema, setSchema] = useState<FieldNode[]>([]);
  const [document, setDocument] = useState<Document>(STARTING_DOCUMENT);
  const [problems, setProblems] = useState<string[]>([]);
  const [status, setStatus] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [skin, setSkin] = useState<SkinSummary | null>(null);
  const [revision, setRevision] = useState(0);

  // One scratch handle for the whole session, so recompiling an edit replaces
  // the previous compilation instead of accumulating one per keystroke.
  const handle = useMemo(() => `draft:${skinId ?? 'new'}`, [skinId]);

  useEffect(() => {
    let cancelled = false;
    void initWasm().then((wasm) => {
      if (cancelled) {
        return;
      }
      try {
        setSchema(JSON.parse(wasm.skinDocSchema()) as FieldNode[]);
      } catch (cause) {
        setProblems([`The editor could not read the skin schema: ${String(cause)}`]);
      }
    });
    return () => {
      cancelled = true;
    };
  }, []);

  // Recompile on every settled edit. Compilation runs the same validator the
  // server runs, so the preview and the save agree about what is valid.
  useEffect(() => {
    const wasm = getWasm();
    if (!wasm || schema.length === 0) {
      return;
    }
    try {
      wasm.registerDraftSkin(handle, JSON.stringify(document));
      setProblems([]);
      setRevision((current) => current + 1);
    } catch (cause) {
      setProblems([String(cause)]);
    }
  }, [document, handle, schema.length]);

  const change = useCallback((path: string, value: unknown) => {
    setDocument((current) => write(current, path, value));
    setStatus(null);
  }, []);

  const save = useCallback(async () => {
    if (!user) {
      onOpenAuth();
      return;
    }
    setSaving(true);
    setStatus(null);
    try {
      const name = (document.name as string) ?? 'My skin';
      if (skin) {
        const updated = await api.updateSkin(skin.skinId, { name, document });
        setSkin(updated);
        setStatus('Saved.');
      } else {
        const created = await api.createSkin({ name, document });
        setSkin(created);
        setStatus('Saved.');
        navigate(`/skins/builder/${created.skinId}`, { replace: true });
      }
    } catch (cause) {
      setProblems([isApiError(cause) ? cause.message : String(cause)]);
    } finally {
      setSaving(false);
    }
  }, [document, navigate, onOpenAuth, skin, user]);

  const requestReview = useCallback(async () => {
    if (!skin) {
      return;
    }
    try {
      await api.requestSkinPublication(skin.skinId);
      setStatus('Sent for review.');
    } catch (cause) {
      setProblems([isApiError(cause) ? cause.message : String(cause)]);
    }
  }, [skin]);

  return (
    <div className="home-page builder-page">
      <HomeHeader
        activePage="skins"
        currentUser={user}
        lobbyMembers={[]}
        hasLobby={false}
        onInvite={() => {}}
        onJoinGame={() => {}}
        onLeaveLobby={() => {}}
        onAuthClick={onOpenAuth}
        onOpenAccount={onOpenAccount}
        onLogout={logout}
      />

      <main className="builder-main">
        <div className="builder-intro">
          <h1 className="builder-title">Skin Builder</h1>
          <p className="builder-subtitle">
            Every control here comes from the skin format itself, so the editor
            can never fall behind what a skin can be.
          </p>
        </div>

        <div className="builder-preview-strip">
          {PREVIEW_POSES.map((preview) => (
            <BuilderPreview
              key={`${preview.pose}-${preview.role}`}
              handle={handle}
              pose={preview.pose}
              role={preview.role}
              label={preview.label}
              revision={revision}
              valid={problems.length === 0}
            />
          ))}
        </div>

        {problems.length > 0 ? (
          <ul className="builder-problems" role="alert">
            {problems.map((problem) => (
              <li key={problem}>{problem}</li>
            ))}
          </ul>
        ) : null}

        {status ? <p className="builder-status" role="status">{status}</p> : null}

        <div className="builder-actions">
          <button
            type="button"
            className="game-shell-button is-primary"
            onClick={() => void save()}
            disabled={saving}
          >
            {skin ? 'Save revision' : 'Save skin'}
          </button>
          {skin ? (
            <button
              type="button"
              className="game-shell-button"
              onClick={() => void requestReview()}
              disabled={problems.length > 0}
            >
              Send for review
            </button>
          ) : null}
        </div>

        <form className="builder-form" onSubmit={(event) => event.preventDefault()}>
          {schema.map((field) => (
            <Control
              key={field.path}
              field={field}
              document={document}
              onChange={change}
            />
          ))}
        </form>
      </main>
    </div>
  );
};

interface BuilderPreviewProps {
  handle: string;
  pose: string;
  role: string;
  label: string;
  revision: number;
  valid: boolean;
}

/**
 * One preview pose, always animating.
 *
 * A builder needs to see motion — a skin frozen at one frame hides half of what
 * an animation does — so unlike the browse page these never stop.
 */
const BuilderPreview: React.FC<BuilderPreviewProps> = ({
  handle,
  pose,
  role,
  label,
  revision,
  valid,
}) => {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [layout, setLayout] = useState({
    canvasWidth: 370,
    canvasHeight: 150,
    cropWidth: 370,
    cropHeight: 60,
    offsetX: 0,
    offsetY: 54,
  });

  // Fixture poses paint at their own arena coordinates rather than at the
  // origin, so the canvas has to be tall enough to reach the pose and the
  // wrapper crops back to it. Without this a strip of three previews is mostly
  // empty space.
  useEffect(() => {
    const wasm = getWasm();
    if (!wasm || !valid) {
      return;
    }
    try {
      const bounds = JSON.parse(
        wasm.skinFixtureBounds(handle, pose, PREVIEW_CELL, false),
      ) as { x: number; y: number; width: number; height: number };
      setLayout({
        canvasWidth: Math.ceil(bounds.x + bounds.width + PREVIEW_PAD),
        canvasHeight: Math.ceil(bounds.y + bounds.height + PREVIEW_PAD),
        cropWidth: Math.ceil(bounds.width + PREVIEW_PAD * 2),
        cropHeight: Math.ceil(bounds.height + PREVIEW_PAD * 2),
        offsetX: Math.round(bounds.x - PREVIEW_PAD),
        offsetY: Math.round(bounds.y - PREVIEW_PAD),
      });
    } catch {
      // Keep the previous framing; a slightly wrong one beats none.
    }
  }, [handle, pose, revision, valid]);

  useEffect(() => {
    const canvas = canvasRef.current;
    const wasm = getWasm();
    if (!canvas || !wasm || !valid) {
      return;
    }
    let frame = requestAnimationFrame(function loop(now: number) {
      try {
        wasm.renderSkinFixture(
          canvas,
          handle,
          pose,
          role,
          PREVIEW_CELL,
          false,
          false,
          now,
          false,
        );
      } catch {
        // An invalid draft leaves the last good frame up; the problem list
        // beside it is what says why.
      }
      frame = requestAnimationFrame(loop);
    });
    return () => cancelAnimationFrame(frame);
  }, [handle, pose, role, revision, valid, layout.canvasWidth, layout.canvasHeight]);

  return (
    <figure className="builder-preview">
      <div
        className="builder-preview-crop"
        style={{ width: layout.cropWidth, height: layout.cropHeight }}
      >
        <canvas
          ref={canvasRef}
          width={layout.canvasWidth}
          height={layout.canvasHeight}
          style={{ marginLeft: -layout.offsetX, marginTop: -layout.offsetY }}
          role="img"
          aria-label={label}
        />
      </div>
      <figcaption>{label}</figcaption>
    </figure>
  );
};

export default SkinBuilder;
